- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
- Swashbuckle.Core/Swagger/SchemaRegistry.cs
- Swashbuckle.Core/Swagger/SwaggerGenerator.cs
- Swashbuckle.Core/Swagger/SwaggerGeneratorSettings.cs
- Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs
- Swashbuckle.Dummy.WebHost/Global.asax.cs
Related to issue #131, we don't have a reference to Json.Net in our models assembly so we've always used 
```
var jsonFormatter = GlobalConfiguration.Configuration.Formatters.JsonFormatter;
jsonFormatter.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
```
to configure the global formatters. Because of that we can't rely on the individual enums having the proper attributes so we need a way to tell swashbuckle how to use it. 
This PR hard codes true for the override, but there shouldn't be a reason the default couldn't be to query the global formatters looking to see if StringEnumConverter is in there.
One note - it seems that once you set StringEnumConverter globally there isn't a good way to force int enums on individual items. That's why I went …
> allowing the ability to force the use of string enums

- Swashbuckle.Core/Application/SwaggerSpecConfig.cs
- Swashbuckle.Core/SwaggerExtensions/HandleComplexTypesFromUri.cs
- Swashbuckle.Core/Swashbuckle.Core.csproj
- Swashbuckle.Dummy.Core/Controllers/ParamsFromUriController.cs
- Swashbuckle.Dummy.Core/Swashbuckle.Dummy.Core.csproj
- Swashbuckle.Tests/SwaggerSpec/CoreTests.cs
I can't support Swagger 2.0 yet.  I needed this fix in Swashbuckle version 4, so backported the changes from #70.
> Added support for complex types in [FromUri] in Swashbuckle version 4

- Swashbuckle.Core/Application/SwaggerSpecConfig.cs
- Swashbuckle.Core/SwaggerExtensions/HideObsoleteModelFields.cs
- Swashbuckle.Core/Swashbuckle.Core.csproj
- Swashbuckle.Dummy.Core/Controllers/ObsoleteModelFieldsController.cs
- Swashbuckle.Dummy.Core/Swashbuckle.Dummy.Core.csproj
- Swashbuckle.Tests/SwaggerSpec/ModelTests.cs
A common occurrence as APIs evolve is to mark model fields `[Obsolete]`.
We usually retain the prior fields for backwards compatibility (sometimes just for a small migration window), but we don't want to advertize them in documentation.
This is opt-**in** behavior, (`c.IgnoreObsoleteModelFields()`)
> Add ability to hide model fields that are [Obsolete]

- Swashbuckle.Core/Swagger/Filters/ApplyXmlTypeComments.cs
- Swashbuckle.Dummy.Core/Controllers/XmlAnnotatedController.cs
- Swashbuckle.Dummy.Core/XmlComments.xml
- Swashbuckle.Dummy.WebHost/XmlComments.xml
- Swashbuckle.Tests/Swagger/XmlCommentsTests.cs
Derived classes were not getting descriptions for properties that came from a base class. I updated ApplyXmlTypeComments to pull the comments from base classes.
> Updated ApplyXmlTypeComments to pull Property comments from base classes

- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
- Swashbuckle.Tests/Swagger/CoreTests.cs
- Swashbuckle.Tests/Swagger/DefaultRootUrlResolverTests.cs
- Swashbuckle.Tests/Swashbuckle.Tests.csproj
Changed DefaultRootUrlResolver to support X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Port headers.
Added unit tests for that.
Added missing assert to existing unit test and split up existing unit test into 2.
> Change DefaultRootUrlResolver to support X-Forwarded headers

- README.md
The call to req.GetConfiguration() in default BasePathResolver implementation requires VirtualPathRoot to be specified in HttpConfiguration at startup.
I first wanted to make a PR that would fix this in code, but you seem to be still targeting WebApi v1, where GetRequestContext() is not supported. So here's at least a workaround recipe.
> Document OWIN VirtualPathRoot workaround

- Swashbuckle.Core/Swagger/Filters/ApplyXmlActionComments.cs
- Swashbuckle.Core/Swagger/Filters/ApplyXmlTypeComments.cs
- Swashbuckle.Core/Swagger/XmlExtensions.cs
- Swashbuckle.Core/Swashbuckle.Core.csproj
- Swashbuckle.Dummy.Core/Controllers/XmlAnnotatedController.cs
- Swashbuckle.Dummy.Core/XmlComments.xml
- Swashbuckle.Dummy.WebHost/XmlComments.xml
- Swashbuckle.Tests/Swagger/XmlCommentsTests.cs
This PR adds support for <paramref>, <see> and <c> blocks in XML comments by wrapping the content of them within curly braces.
This way, the text appears in the documentation instead of being omitted.  The current method (node.InnerText) omits anything that falls inside a child node.
> Added support for XML comments.  Fixes #188

- Swashbuckle.Core/SwaggerUi/EmbeddedAssetProvider.cs
- Swashbuckle.Tests/SwaggerUi/SwaggerUiTests.cs
Added mime-types for the fonts that are contained in the `swagger-ui/src/html/fonts` folder.
They were previously served as "text/html", discovered through a Chrome console warning:
> Resource interpreted as Font but transferred with MIME type text/html: "/docs/fonts/droid-sans-v6-latin-700-woff2".
> Missing mime types

- README.md
Since the default redirect route isn't created when a custom swagger-ui route template is used users may need a little help finding it
> noted how to get to ui when its url changes

- Swashbuckle.Core/Swagger/XmlComments/ApplyXmlTypeComments.cs
I just noticed that if you have an action that returns a model with one or more public fields, an unhandled exception is thrown in **ApplyXmlTypeComments.ApplyPropertyComments()**.
It looks like this happens because **JsonPropertyExtensions.PropertyInfo()** calls **GetProperty()**, which will null for a field and there is no protection inside **ApplyXmlTypeComments.ApplyPropertyComments()** for a null **memberInfo** argument.
I realize it is a bit of an odd case (public fields on classes), but it took a little digging for me to figure out why this was happening when I added to one of our existing APIs so I thought it was worth suggesting.
> Add null check for memberInfo parameter.

- Swashbuckle.Core/Swagger/FromUriParams/HandleFromUriParams.cs
- Swashbuckle.Dummy.Core/Controllers/XmlAnnotatedController.cs
- Swashbuckle.Dummy.Core/XmlComments.xml
- Swashbuckle.Dummy.WebHost/XmlComments.xml
- Swashbuckle.Tests/Swagger/XmlCommentsTests.cs
Swashbuckle has the ability to generate parameters from a complex type when marked with the FromUri-attribute, like so:
```c#
public IHttpActionResult Get([FromUri] Page page) { /* ... */ }
public class Page 
{ 
/// <summary>
/// The maximum number of items
/// </summary>
public int Limit { get; set; }
/// <summary>
/// Offset number of items into result
/// </summary>
public int Offset { get; set; } 
}
```
When pairing this with XML-comments however the expected behavior, in my opinion, is that the parameters should get their description from the summary tags of the properties of the complex type, which is not currently the case. 
This pull request fixes this issue, and adds a unit test to verify that the summary tags from the XML-comment is carried over to the generated parameters.
An …
> Fetch description from summary tags when using FromUri-attribute

- Swashbuckle.Core/Swagger/JsonPropertyExtensions.cs
In some scenarios the jsonProperty.UnderlyingName is null. For instance if we have custom contract resolvers like in https://github.com/kekekeks/hal-json-net/blob/5292c6f85c819e5fbcd26c13afe79aff3becfc04/HalJsonNet/Serialization/JsonNetHalJsonContactResolver.cs#L60 that inject custom values in the response.
As a side effect of this change the response model will default to object.
Note that without this, the API swagger generation process throw an exception.
> Handle null jsonProperty.UnderlyingName values

- .gitignore
- Swashbuckle.Core/Swagger/SwaggerDocument.cs
Changed Response.headers from IList&lt;Header> to IDictionary&lt;string, Header>
- IList generates array, and it is not possible to specify header name
- Swagger 2.0 spec says it is supposed to be object in form { 'header-name': Header, 'another-header': Header }
> Changed Response.headers from IList<Header> to IDictionary<string, Header>

- Swashbuckle.Core/Swagger/SchemaExtensions.cs
- Swashbuckle.Dummy.Core/Controllers/AnnotatedTypesController.cs
- Swashbuckle.Tests/Swagger/SchemaTests.cs
The current Swagger specification allows to set a maximum and a minimum length in the schema definition. The fields themselves are already in the object specification itself, but aren't used currently.
The allowed lengths can be set in .NET by the "StringLengthAttribute" on the fields.
I added the logic to test for them, and set the lengths if available. It is also added in the unit tests, which worked fine.
> Maximum and Minimum Length in Schema

- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
- Swashbuckle.Core/Swagger/SchemaRegistry.cs
- Swashbuckle.Core/Swagger/SwaggerGenerator.cs
- Swashbuckle.Core/Swagger/SwaggerGeneratorOptions.cs
- Swashbuckle.Tests/Swagger/SchemaTests.cs
This resolves issue #333.
I kept UseFullTypeNameInSchemaIds in config api but removed it from other classes. The tests only cover the config api so I when with a breaking change to keep the implementation cleaner.
Let me know if this is a problem I can probably do a backward compatible patch if needs be.
> Strategy to create schema ids

- Swashbuckle.Core/Application/SwaggerUiConfig.cs
- Swashbuckle.Core/SwaggerUi/CustomAssets/index.html
- Swashbuckle.Core/SwaggerUi/CustomAssets/screen.css
- Swashbuckle.Core/SwaggerUi/CustomAssets/swagger-oauth.js
Hi,
Please pull this change in order to upgrade Swashbuckle to use the latest stable version of Swagger-UI (v2.1.1). The current Swashbuckle implementation uses v2.1.0, while the latest Swagger-UI contains various bug fixes and features.
I originally updated the Swagger-UI version so that I could use the OAuth2 Authorizarion Code flow in the UI in order to test my APIs (see https://github.com/swagger-api/swagger-ui/issues/1384).
> Update to Swagger-UI v2.1.1

- Swashbuckle.Core/Swagger/SwaggerGenerator.cs
Swashbuckle is putting the port in the host address. But if it's a default port, it's not necessary. In some cases, it's not desired inclusive.
> Remove port if is default

- README.md
Also changed "WebApi" to "Web API", since that's the official name (it's very generic, but that's how it is).
"config. interface" changed to "configuration API", since "interface" in some places sounded more like a GUI thing.
> Fixed a couple of spelling errors

- Swashbuckle.Core/Swagger/TypeExtensions.cs
The issue is encountered when using generic types in MVC controllers. Tested.
> Fixes null ref exception when a generic type 'T' is passed in.

- README.md
Custom routes section contained wrong description about swagger-ui route.
in case when you EnableSwaggerUi("sandbox/{*assetPath}") the correct url will be 'sandbox/index'
> Fix custom route sample mistake

- Swashbuckle.Core/Swagger/SchemaRegistry.cs
- Swashbuckle.Core/Swashbuckle.Core.csproj
- Swashbuckle.Dummy.Core/Controllers/DataContractAnnotatedTypesController.cs
- Swashbuckle.Dummy.Core/Swashbuckle.Dummy.Core.csproj
This is one option for fixing #562 
I think the best way would be to rely on json.net's serializer to format the name, falling back to the current implementation if one isn't available - the problem is I couldn't spot an easy way to do that.
This is probably the "next best" option - rather using type.GetEnumNames, implement a new GetEnumNames method that is similar, but has some understanding of the EnumValue attribute. The main drawback is the new dependency on System.Runtime.Serialization, but given you're relying on JSON.NET you've already got an indirect dependency there.
Hope that helps.
> Cater for value names defined in EnumMember attributes

- Swashbuckle.Core/Application/SwaggerUiConfig.cs
- Swashbuckle.Core/SwaggerUi/CustomAssets/index.html
- Swashbuckle.Core/SwaggerUi/CustomAssets/swagger-oauth.js
- Swashbuckle.Tests/SwaggerUi/SwaggerUiTests.cs
Hi, while trying to integrate an Azure Active Directory (AAD) protected API with Swashbuckle and Swagger-UI I encountered the issue where it is required to specify the "Resource" parameter during OAuth2 authorization but there was no way of easily providing it. This problem is covered in issues https://github.com/domaindrivendev/Swashbuckle/issues/465 and https://github.com/swagger-api/swagger-ui/issues/1302.
I made a generic mechanism for passing custom parameters (instead of adding a specific "Resource" parameter) since I also really needed a custom parameter "domain_hint" as explained here - http://www.cloudidentity.com/blog/2014/11/17/skipping-the-home-realm-discovery-page-in-azure-ad/.
This change corresponds to a pull request on Swagger-UI I opened as well …
> Support additional query parameters during OAuth2 authorization process

- Swashbuckle.Core/Swagger/SchemaRegistry.cs
Addresses issue #640 by fixing CreatePrimitiveSchema to handle Byte[] as byte formatted string instead of Byte which should just be handled as a integer.
Replaces pull request #641.
> Handle byte as integer, byte[] as string format=byte

- Swashbuckle.Core/Swagger/SchemaRegistry.cs
In Swagger, GUIDs/UUIDs can have the custom format "uuid" specified so that the appropriate language primitive can be used when generating code. For example, in the C# Swagger generator, this will cause the generated property to have type System.Guid instead of System.String: https://github.com/swagger-api/swagger-codegen/blob/b00971edc9005a7c2c95d8c9f87beb1b1153a962/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java#L117
The same also applies to the Java generator.
This pull request simply adds that mapping to Swashbuckle's schema generator.
> Set format to 'uuid' for System.Guid

- .gitignore
- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
Overload added. I didn't write any tests, because it seemed not reasonable to duplicate existing tests and I am not aware of any better way. Let me know if you would like to add some tests and I will take care of it.
> Add non-generic overload of SwaggerDocsConfig.MapType, issue #643

- Swashbuckle.Core/Application/HttpConfigurationExtensions.cs
- Swashbuckle.Tests/Owin/BaseInMemoryOwinSwaggerTest.cs
- Swashbuckle.Tests/Owin/InMemoryOwinTest.cs
- Swashbuckle.Tests/Owin/MultiSwaggerOwinStartup.cs
- Swashbuckle.Tests/Owin/OwinStartup.cs
- Swashbuckle.Tests/Owin/PredefinedHttpControllerSelector.cs
- Swashbuckle.Tests/Swashbuckle.Tests.csproj
- Swashbuckle.Tests/app.config
- Swashbuckle.Tests/packages.config
This resolves #718 .
* The fix is just 2 lines: make http route config name unique, instead of using a constant (such as `swagger_docs`), it was made unique by adding route_template (`"swagger_docs" + routeTemplate)
* Added 2 tests - one tests that a default endpoint for swagger can be poked, the other adds an extra endpoint for swagger spec. The latter is what was failing.
* The tests are running a full in-memory owin pipeline, so we get to test `HttpConfigurationExtensions` and `SwaggerEnabledConfiguration`, which was previously completely uncovered. 
* To have in memory owin tests, a number of packages had to be brought into testing project. Let me know if this is an issue or not.
> #718 Adding support for having multiple swagger endpoints

- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
- Swashbuckle.Core/Swagger/SchemaExtensions.cs
- Swashbuckle.Core/Swagger/SchemaRegistry.cs
- Swashbuckle.Core/Swagger/SwaggerDocument.cs
- Swashbuckle.Core/Swagger/SwaggerGenerator.cs
- Swashbuckle.Core/Swagger/SwaggerGeneratorOptions.cs
- Swashbuckle.Core/Swagger/XmlComments/ApplyXmlTypeComments.cs
- Swashbuckle.Dummy.Core/Controllers/PrimitiveArrayTypesController.cs
- Swashbuckle.Dummy.Core/Controllers/PrimitiveTypesController.cs
- Swashbuckle.Dummy.Core/SwaggerExtensions/ApplySchemaVendorExtensions.cs
- Swashbuckle.Dummy.Core/Swashbuckle.Dummy.Core.csproj
- Swashbuckle.Dummy.Core/Types/PrimitiveEnum.cs
- Swashbuckle.Tests/Swagger/SchemaTests.cs
Following up from #776; make `ISchemaFilter` available for all types.
Unit tests use a `ISchemaFilter` to demonstrate this for all primitives (including enums), composites and arrays, including with nullable types, used in parameters and request / response types.
This could be made available in a separate AutoRest extension as follows:
```c#
public class XmsTypeDotNetSchemaFilter : ISchemaFilter
{
public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
{
if (type.IsArray && type.GetElementType() != typeof(byte)) return; // Special case
var nullableUnderlyingType = Nullable.GetUnderlyingType(type);
schema.vendorExtensions.Add("x-type-dotnet", (nullableUnderlyingType ?? type).FullName);
schema.vendorExtensions.Add("x-nullable", nullableUnderlyingType != null || …
```
> Apply schema filters everywhere

- Swashbuckle.Core/SwaggerUi/CustomAssets/index.html
See https://tools.ietf.org/html/rfc6749 section 3.1.2.
Without the fix this pull request proposes, invalid `redirect_uri`s are generated such as: 
`http://localhost:49242/swagger/ui/o2c-html#!/Assets/Assets_GetAll`
> Oauth2 spec does not allow redirect uris to contain a fragment component

- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
- Swashbuckle.Core/Swagger/XmlComments/ApplyXmlActionComments.cs
- Swashbuckle.Core/Swagger/XmlComments/ApplyXmlTypeComments.cs
Improve performance of `swagger/docs/{version}` call when using XML comment documents.
Based off of https://github.com/domaindrivendev/Swashbuckle/pull/858
> Perf: IncludeXmlComments() shares XPathDocument instances.

- README.md
When using `FromUri` Model Binding, duplicate items can appear as items can be passed as URI parameters, or querystrings. In this case you can add a custom operation filter to remove the duplicates. 
Also added `csharp` markdown styling
> Updated documentation - how to remove duplicates

- README.md
This example only applies to 4.0 but this documentation is specific to 5.0 so it is confusing to new users like me.
> Eliminate 4.0 examples in documentation

- Swashbuckle.Core/SwaggerUi/CustomAssets/index.html
Proposing this PR to resolve https://github.com/domaindrivendev/Swashbuckle/issues/851. 
The code change in this PR makes it so that when using ApiKey Authentication, the key value is URI encoded only when in "query" mode. In "header" mode the key value is not URI encoded thereby resolving said issue.
> Only "URI encoding" ApiKey when in "query" mode.

- README.md
When XML documentation is required, but isn't configured correctly in the project file, you will get a 500 error. Added a note to the readme to catch this case.
> Added FAQ for 500 error

- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
Prevent SchemaFilter and DocumentFilter factories to be called multiple times. Fixes issue #960 .
However if the intend was that the SchemaFilter and DocumentFilter are both constructed multiple times, this pull-request should be rejected.
> #960 Prevent SchemaFilter and DocumentFilter factories to be called multiple times.

- README.md
This morning i tried to follow the link to the Swashbuckle.AspNetCore page and it 404d with some encoded characters being generated at the end of the link.
> Fix AspNetCore link on Readme.md

- Swashbuckle.Core/Application/SwaggerUiHandler.cs
If other services will use custom "HttpMessageHandler" to modify responses they can receive null reference error if will try to access "RequestMessage".
> #1024 missing RequestMessage

- Swashbuckle.Dummy.Core/Controllers/FileDownloadController.cs
We hit an error for download files with content dispositions due to incorrect use of the `URL.createObjectURL` function when using blobs in the swagger ui. This is fixed in newer versions of swagger ui, but Swashbuckle use an older version.
This PR upgrades the swagger-ui submodule to the latest release (v2.2.10) and additionally adds an controller endpoint testing verifying the issue with swagger-ui.
I couldn't find any way to verify/test swagger-ui except the override controls as tests and manually testing the dummy selfhost. But all looks good to me and I couldn't find any broken features (nor should there be any breaking changes in the swagger-ui package).
Let me know if there's anything else you need from me.
> Upgrades Swagger UI to v2.2.10

- README.md
The 'base' file for custom index.html still linked to 5.2.1, this fails on jsoneditor. I put 5.3.2 instead.
From personal experience, discourage using 'swagger' as a folder name for custom assets.
> Changes to readme for custom assets

- Swashbuckle.Core/Swagger/JsonPropertyExtensions.cs
Fix to also check the Required property of the JsonProperty when determining if a model property is required or optional.
> Fix to also check the Required property of the JsonProperty

- Swashbuckle.Core/Application/SwaggerDocsConfig.cs
- Swashbuckle.Tests/Swagger/DefaultRootUrlResolverTests.cs
I've noticed that regardless of where the swagger documents are hosted, the URI of the swagger spec always includes the port, even if it uses the protocol default port i.e. 80 for http and 443 for https.
This update:
* alters the `DefaultRootUrlResolver` to use a `UriBuilder` handle the decision of including the port of not (instead of using string concatenation)
* adds new tests for omitting the port from the url when applicable
This will result in urls like `http://tempuri.org/swaggger/docs/1` instead of `http://tempuri.org:80/swaggger/docs/1`.
> Removes default ports from `DefaultRootUrlResolver` when applicable

- Swashbuckle.Core/Swagger/SchemaRegistry.cs
- Swashbuckle.Core/Swashbuckle.Core.csproj
- Swashbuckle.Core/Swashbuckle.Core.nuspec
- Swashbuckle.Core/app.config
- Swashbuckle.Core/packages.config
- Swashbuckle.Dummy.Core/Swashbuckle.Dummy.Core.csproj
- Swashbuckle.Dummy.Core/app.config
- Swashbuckle.Dummy.Core/packages.config
- Swashbuckle.Dummy.SelfHost/Swashbuckle.Dummy.SelfHost.csproj
- Swashbuckle.Dummy.SelfHost/app.config
- Swashbuckle.Dummy.SelfHost/packages.config
- Swashbuckle.Dummy.WebHost/Swashbuckle.Dummy.WebHost.csproj
- Swashbuckle.Dummy.WebHost/Web.config
- Swashbuckle.Dummy.WebHost/packages.config
- Swashbuckle.Tests/Swashbuckle.Tests.csproj
- Swashbuckle.Tests/app.config
- Swashbuckle.Tests/packages.config
Newtonsoft.Json marked `JsonDictionaryContract.PropertyNameResolver` as obsolete and added `JsonDictionaryContract.DictionaryKeyResolver` on v7.0.1. They removed `JsonDictionaryContract.PropertyNameResolver` on v10.0.1.
I've updated Newtonsoft.Json to v7.0.1 and changed `JsonDictionaryContract.PropertyNameResolver` usage to `JsonDictionaryContract.DictionaryKeyResolver` and also added Newtonsoft.Json >= v7.0.1 dependency to Swashbuckle.Core package.
> Newtonsoft.Json package updated to v7.0.1, issue #1041 fixed.
